version: '3.8'
services:
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "5173:5173" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
   
  backend:
    build: ./backend
    expose:
      - '3000'
    ports: 
      - "3000:3000"
    container_name: backend-docker
    restart: always
    links: 
      - db 

  db:
    image: postgres:15.1-alpine
    container_name: database-ngcash
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=null
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: